version: '3'

services:
  reverse-proxy:
    image: nginx
    restart: always
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - 80:80
#      - 443:443
    environment:
      VIRTUAL_HOST: chillshock.easable.jp
      LETSENCRYPT_HOST: chillshock.easable.jp
      LETSENCRYPT_EMAIL: 2190006@ecccomp.com

#  letsencrypt:
#    image: jrcs/letsencrypt-nginx-proxy-companion
#    restart: always
#    depends_on:
#      - "reverse-proxy"
#    volumes:
#      - ./html:/etc/nginx/vhost.d
#      - ./html:/usr/share/nginx/html
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - ./certs:/etc/nginx/certs:rw
#    environment:
#      NGINX_PROXY_CONTAINER: reverse-proxy
    
networks:
  default:
    external:
      name: nginx-proxy

volumes:
  certs:
    external: true
